---
engines:
  coverage:
    enabled: false
  duplication:
    enabled: true
  metric:
    enabled: true
  eslint:
    enabled: false
  pmd:
    enabled: true
  remarklint:
    enabled: true
  jacksonlinter:
    enabled: true
