---
engines:
  coverage:
    enabled: false
  duplication:
    enabled: true
  metric:
    enabled: true
  eslint:
    enabled: false
languages:
  javascript:
    extensions:
      - '*.js'
  typescript:
      extensions:
        - '*.ts'
