version: 2.1
executors:
  build-executor: 
    docker: 
      - image: circleci/node:12
    resource_class: medium
jobs:
  release:
    executor: build-executor
    steps:
      - checkout
      - run: npx semantic-release@15
  build: 
    executor: build-executor
    steps: 
      - checkout
      - run: 
          name: "Build package"
          command: |
            yarn install
            yarn build

workflows:
  test-and-release:
    jobs:
      - release:
          requires:
            - build
          filters:
            branches:
              only: production
      - build  # Run on all branches

