version: 2.1

executors:
  build-executor: 
    docker: 
      - image: circleci/node:12
    resource_class: small

commands: 
  install_node_modules:
    steps:
      - restore_cache:
          keys: 
            - node-module-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install packages
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn install --frozen-lockfile
      - save_cache: # special step to save the dependency cache
          key: node-module-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  release:
    executor: build-executor
    steps:
      - checkout
      - run: npx semantic-release@15
  build: 
    executor: build-executor
    steps: 
      - checkout
      - install_node_modules
      - run: 
          name: "Build package"
          command: |
            yarn build

workflows:
  test-and-release:
    jobs:
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
      - build  # Run on all branches

