version: 2.1

executors:
  build-executor: 
    docker: 
      - image: circleci/node:12
    resource_class: small

jobs:
  release:
    executor: build-executor
    steps:
      - checkout
      - run: npx semantic-release@15
  build: 
    executor: build-executor
    steps: 
      - checkout
      - run: 
          name: "Install dependencies"
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn install --frozen-lockfile
      - run: 
          name: "Build package"
          command: |
            yarn build

workflows:
  test-and-release:
    jobs:
      - release:
          requires:
            - build
          filters:
            branches:
              only: production
      - build  # Run on all branches

